# Generated by Django 4.2.3 on 2025-07-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_submission_question_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='choice',
            name='content',
            field=models.CharField(default='placeholder', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.CharField(default='placeholder', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=50),
        ),
    ]
